declare const NODE_ENV: string, NAME: string, CAYLEY_ADDRESS: string, KNOWLEDGE_ADDRESS: string, KAFKA_ADDRESS: string, INPUT_TOPIC: string, ELASTICSEARCH_ADDRESS: string, ELASTICSEARCH_INDEX_NAME: string, ELASTICSEARCH_USE_ALIASES: string | boolean;
declare const VERSION: any;
declare const INDEX_BATCH_SIZE: number;
export { NAME, NODE_ENV, ELASTICSEARCH_ADDRESS, CAYLEY_ADDRESS, KNOWLEDGE_ADDRESS, KAFKA_ADDRESS, INPUT_TOPIC, ELASTICSEARCH_INDEX_NAME, ELASTICSEARCH_USE_ALIASES, INDEX_BATCH_SIZE, VERSION };
