"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').load({ silent: true });
const { NAME = 'feedbackfruits-knowledge-search-broker', ELASTICSEARCH_ADDRESS = 'http://localhost:9200', CAYLEY_ADDRESS = 'http://cayley:64210', KNOWLEDGE_ADDRESS = 'https://staging-api.explain.direct', KAFKA_ADDRESS = 'tcp://localhost:9092', INPUT_TOPIC = 'staging_updates', ELASTICSEARCH_INDEX_NAME = 'knowledge', } = process.env;
exports.NAME = NAME;
exports.ELASTICSEARCH_ADDRESS = ELASTICSEARCH_ADDRESS;
exports.CAYLEY_ADDRESS = CAYLEY_ADDRESS;
exports.KNOWLEDGE_ADDRESS = KNOWLEDGE_ADDRESS;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.INPUT_TOPIC = INPUT_TOPIC;
exports.ELASTICSEARCH_INDEX_NAME = ELASTICSEARCH_INDEX_NAME;
