declare const NAME: string, CAYLEY_ADDRESS: string, KNOWLEDGE_ADDRESS: string, KAFKA_ADDRESS: string, INPUT_TOPIC: string, ELASTICSEARCH_ADDRESS: string, ELASTICSEARCH_INDEX_NAME: string;
export { NAME, ELASTICSEARCH_ADDRESS, CAYLEY_ADDRESS, KNOWLEDGE_ADDRESS, KAFKA_ADDRESS, INPUT_TOPIC, ELASTICSEARCH_INDEX_NAME };
