"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').load({ silent: true });
const { NAME = 'feedbackfruits-knowledge-search-broker-v25', ELASTICSEARCH_ADDRESS = 'http://localhost:9200', GIZMO_ENDPONT = 'http://staging-fbf-cayley.herokuapp.com/api/v1/query/gizmo', KNOWLEDGE_ADDRESS = 'https://staging-api.explain.direct', KAFKA_ADDRESS = 'tcp://kafka:9092', INPUT_TOPIC = 'staging_quad_updates', ELASTICSEARCH_INDEX_NAME = 'knowledge', } = process.env;
exports.NAME = NAME;
exports.ELASTICSEARCH_ADDRESS = ELASTICSEARCH_ADDRESS;
exports.GIZMO_ENDPONT = GIZMO_ENDPONT;
exports.KNOWLEDGE_ADDRESS = KNOWLEDGE_ADDRESS;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.INPUT_TOPIC = INPUT_TOPIC;
exports.ELASTICSEARCH_INDEX_NAME = ELASTICSEARCH_INDEX_NAME;
