declare const NAME: any, CAYLEY_ADDRESS: any, KNOWLEDGE_ADDRESS: any, KAFKA_ADDRESS: any, INPUT_TOPIC: any, ELASTICSEARCH_ADDRESS: any, ELASTICSEARCH_INDEX_NAME: any;
declare const INDEX_BATCH_SIZE: number;
export { NAME, ELASTICSEARCH_ADDRESS, CAYLEY_ADDRESS, KNOWLEDGE_ADDRESS, KAFKA_ADDRESS, INPUT_TOPIC, ELASTICSEARCH_INDEX_NAME, INDEX_BATCH_SIZE };
